services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb_container
    environment:
      - MONGODB_URI
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
    

volumes:
  mongodb_data:
    driver: local
